version: "3.8"
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net
  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - index_data:/rabbitmq
    ports:
      - 5672:5672
    networks:
      - net
  redis:
    image: redis:latest
    volumes:
      - index_data:/redis
    ports:
      - 6379:6379
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge